#!/usr/bin/env python3
# HAEUN-16 minimal assembler -> hex list + program.mi
# Usage: python asm.py programs/demo.asm

import re
import sys

OP = {
    "NOP": 0x0,
    "LOAD": 0x1,
    "STORE": 0x2,
    "ADD": 0x3,
    "SUB": 0x4,
    "AND": 0x5,
    "OR": 0x6,
    "XOR": 0x7,
    "JMP": 0x8,
}

REG = {"R0": 0, "R1": 1, "R2": 2, "R3": 3}


def parse_line(line):
    line = line.split(";")[0].strip()
    if not line:
        return None
    parts = re.split(r"[,\s]+", line.upper())
    op = parts[0]
    if op not in OP:
        raise ValueError(f"unknown op: {op}")
    oc = OP[op]
    if op == "NOP":
        return oc << 12
    if op == "LOAD":
        rd, imm = parts[1], int(parts[2])
        return (oc << 12) | (REG[rd] << 10) | (imm & 0xFF)
    if op == "STORE":
        rs, imm = parts[1], int(parts[2])
        return (oc << 12) | (REG[rs] << 8) | (imm & 0xFF)
    if op == "JMP":
        imm = int(parts[1])
        return (oc << 12) | (imm & 0xFF)
    if op in ("ADD", "SUB", "AND", "OR", "XOR"):
        rd, rs = parts[1], parts[2]
        return (oc << 12) | (REG[rd] << 10) | (REG[rs] << 8)
    raise ValueError(f"bad line: {line}")


def main():
    if len(sys.argv) < 2:
        print("Usage: python asm.py <file.asm>")
        sys.exit(1)
    path = sys.argv[1]
    words = []
    with open(path, encoding="utf-8") as f:
        for n, raw in enumerate(f, 1):
            try:
                w = parse_line(raw)
                if w is not None:
                    words.append(w)
            except ValueError as e:
                print(f"{path}:{n}: {e}")
                sys.exit(1)
    for i, w in enumerate(words):
        print(f"  [{i}] 0x{w:04X}")
    mi_path = path.replace(".asm", ".mi")
    if mi_path == path:
        mi_path = "program.mi"
    with open(mi_path, "w", encoding="utf-8") as out:
        out.write("# generated by asm.py\n")
        for w in words:
            out.write(f"{w:04X}\n")
    print(f"Wrote {mi_path} ({len(words)} words)")


if __name__ == "__main__":
    main()
