#!/usr/bin/env python3
# HAEUN-16 assembler (2-pass, labels) -> hex list + .mi
# Usage: python asm.py programs/boot.asm
#        python asm.py programs/boot.asm --verilog  (ram_fpga initial snippet)

import re
import sys

OP = {
    "NOP": 0x0,
    "LOAD": 0x1,
    "STORE": 0x2,
    "ADD": 0x3,
    "SUB": 0x4,
    "AND": 0x5,
    "OR": 0x6,
    "XOR": 0x7,
    "JMP": 0x8,
    "JZ": 0x9,
    "CALL": 0xA,
    "RET": 0xB,
    "OUT": 0xC,
    "IN": 0xD,
}

REG = {"R0": 0, "R1": 1, "R2": 2, "R3": 3}

LABEL_RE = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*)\s*:\s*(.*)$")
NUM_RE = re.compile(r"^(\d+)$|^(0x[0-9A-Fa-f]+)$")


def parse_number(tok):
    if tok in REG:
        raise ValueError(f"expected number, got register {tok}")
    if tok.startswith("0X") or tok.startswith("0x"):
        return int(tok, 16)
    return int(tok)


def resolve_operand(tok, labels):
    if tok in labels:
        return labels[tok]
    return parse_number(tok)


def strip_comment(line):
    return line.split(";")[0].strip()


def collect_lines(path):
    lines = []
    with open(path, encoding="utf-8") as f:
        for raw in f:
            text = strip_comment(raw)
            if not text:
                continue
            m = LABEL_RE.match(text)
            if m:
                label, rest = m.group(1).upper(), m.group(2).strip()
                lines.append(("label", label))
                if rest:
                    lines.append(("code", rest))
            else:
                lines.append(("code", text.upper()))
    return lines


def pass1(lines):
    labels = {}
    addr = 0
    for kind, text in lines:
        if kind == "label":
            if text in labels:
                raise ValueError(f"duplicate label: {text}")
            labels[text] = addr
        else:
            addr += 1
    return labels


def encode_line(text, labels):
    parts = re.split(r"[,\s]+", text.strip())
    op = parts[0]
    if op not in OP:
        raise ValueError(f"unknown op: {op}")
    oc = OP[op]
    if op == "NOP":
        return oc << 12
    if op == "RET":
        return oc << 12
    if op == "LOAD":
        rd, imm = parts[1], resolve_operand(parts[2], labels)
        return (oc << 12) | (REG[rd] << 10) | (imm & 0xFF)
    if op == "STORE":
        rs, imm = parts[1], resolve_operand(parts[2], labels)
        return (oc << 12) | (REG[rs] << 8) | (imm & 0xFF)
    if op in ("JMP", "CALL"):
        imm = resolve_operand(parts[1], labels)
        return (oc << 12) | (imm & 0xFF)
    if op == "JZ":
        rd, imm = parts[1], resolve_operand(parts[2], labels)
        return (oc << 12) | (REG[rd] << 10) | (imm & 0xFF)
    if op == "OUT":
        rs, port = parts[1], resolve_operand(parts[2], labels)
        return (oc << 12) | (REG[rs] << 8) | (port & 0xFF)
    if op == "IN":
        rd, port = parts[1], resolve_operand(parts[2], labels)
        return (oc << 12) | (REG[rd] << 10) | (port & 0xFF)
    if op in ("ADD", "SUB", "AND", "OR", "XOR"):
        rd, rs = parts[1], parts[2]
        return (oc << 12) | (REG[rd] << 10) | (REG[rs] << 8)
    raise ValueError(f"bad line: {text}")


def assemble(path):
    lines = collect_lines(path)
    labels = pass1(lines)
    words = []
    for kind, text in lines:
        if kind == "code":
            words.append(encode_line(text, labels))
    return words, labels


def emit_verilog(words, base=0):
    print("        // generated by asm.py --verilog")
    for i, w in enumerate(words):
        print(f"        memory[{base + i}] = 16'h{w:04X};")


def main():
    if len(sys.argv) < 2:
        print("Usage: python asm.py <file.asm> [--verilog]")
        sys.exit(1)
    path = sys.argv[1]
    verilog = "--verilog" in sys.argv[2:]
    try:
        words, labels = assemble(path)
    except ValueError as e:
        print(f"Error: {e}")
        sys.exit(1)

    for name, addr in sorted(labels.items(), key=lambda x: x[1]):
        print(f"  {name}: {addr}")
    for i, w in enumerate(words):
        print(f"  [{i}] 0x{w:04X}")

    mi_path = path.replace(".asm", ".mi")
    if mi_path == path:
        mi_path = "program.mi"
    with open(mi_path, "w", encoding="utf-8") as out:
        out.write("# generated by asm.py\n")
        for w in words:
            out.write(f"{w:04X}\n")
    print(f"Wrote {mi_path} ({len(words)} words)")

    if verilog:
        emit_verilog(words)


if __name__ == "__main__":
    main()
